### ISSUE TITLE
Countable callback not called in IE9 when input characters are deleted

### ISSUE THREAD

**Issue by dcalhoun** [RadLikeWhoa/Countable#30]
There seems to be a [bug in IE9's](http://www.matts411.com/post/internet-explorer-9-oninput/) `oninput` event. The bug causes the event to not fire when characters are deleted (e.g. – backspace, delete, cut).

Countable currently uses `oninput` [if the browser is capable](https://github.com/RadLikeWhoa/Countable/blob/v2.1.0/Countable.js#L30). While IE9 is capable of `oninput`, it might be better to force IE9 to use the `onkeyup` event. IE9 *does* appear to fire `onkeyup` when characters are deleted.

**Comment by RadLikeWhoa** [comment]
Discussion on this issue will be in #31.
