### ISSUE TITLE
use class instead of id

### ISSUE THREAD

**Issue by quasiperfect** [RadLikeWhoa/Countable#32]
hi

thanks for this great script

if there a way to use a class name to assign countable for present and future elements (added by ajax jquery) ?

thanks in advance for your help

**Comment by RadLikeWhoa** [comment]
You can use something like `document.querySelectorAll('.classname')` to bind Countable to multiple elements with the same class, but this only happens once. What you're trying to achieve leans towards event delegation, but this is out of scope for this library.

You can, however, remove the functionality from all affected elements using `Countable.die` and then re-attach the functionality.
