### ISSUE TITLE
Countable.js is missing a trailing semicolon

### ISSUE THREAD

**Issue by mikegioia** [RadLikeWhoa/Countable#33]
I bower include Countable and concatenate the Countable.js file into a build, but there's no trailing ";" in your library and it causes errors when combined with more than one file.

Is there any way you can add this semicolon to the end?

**Comment by RadLikeWhoa** [comment]
I thought of the semicolon at the start of the file, but forgot about the one at the end. Good catch, thanks. :+1:

**Comment by mikegioia** [comment]
Thanks!
