### ISSUE TITLE
li element with value 0 causes original.replace() exception

### ISSUE THREAD

**Issue by paul-muckypuddle** [RadLikeWhoa/Countable#34]
When using countable on an li element with a value, the following error occurs (in Chrome):

    Uncaught TypeError: original.replace is not a function

Tracing this back it's because the li element value is a number, and obviously the replace function belongs to the string prototype. Adding:

       if(typeof(original) !== 'string'){
            original = "";
       }

around line 177 is a kludgy fix... but not great.

**Comment by RadLikeWhoa** [comment]
What exactly does the `li` contain? If it contained a number an easy fix would be to just cast this number to a string.

**Comment by RadLikeWhoa** [comment]
@paul-muckypuddle Any update on this? An isolated test case would be ideal, because I can't seem to reproduce the error.

**Comment by paul-muckypuddle** [comment]
My apologies, I found a workaround at the time to get the project I was
working on finished. Will review this again and update as soon as possible.

On 14 August 2015 at 13:30, Sacha Schmid <notifications@github.com> wrote:

> @paul-muckypuddle <https://github.com/paul-muckypuddle> Any update on
> this? An isolated test case would be ideal, because I can't seem to
> reproduce the error.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RadLikeWhoa/Countable/issues/34#issuecomment-131093154>
> .
>



-- 
*Paul Holmes* | Technical Director
0141 847 0095 | paul@muckypuddle.com
<https://www.facebook.com/muckypuddle>  <https://twitter.com/muckypuddle>
<http://www.pinterest.com/muckypuddle/>
<http://www.linkedin.com/company/mucky-puddle>

**Comment by RadLikeWhoa** [comment]
This issue is resolved in 097b189.
