### ISSUE TITLE
Exclude content from count 

### ISSUE THREAD

**Issue by hamzazar** [RadLikeWhoa/Countable#37]
How can I use countable to solve this problem, I have a HTML like this : 

```HTML
<div class="editor">
      <div class="commentable-section">
	   <div class="editable">
	   </div>
	   <div class="side-comment" >
           </div>
     </div>

     <div class="commentable-section">
	   <div class="editable">
	   </div>
	   <div class="side-comment" >
           </div>
     </div>
</div>
```

So I like to count only .editable section all together,   if I select using .editor class Countable will count also the comments.

**Comment by RadLikeWhoa** [comment]
Countable does not offer an option to exclude child elements from the counter.

For a workaround, I'd suggest something like this:

First of all, all the `.editable` elements need an ID or something.

```js
var editables = document.querySelectorAll('.editor .editable')
var counts = {}

function sumCounts () {
    var totalCounts = {
        'paragraphs': 0,
        'sentences': 0,
        'words': 0,
        'characters': 0,
        'all': 0
    }

    for (var count in counts) {
        for (var field in ['paragraphs', 'sentences', 'words', 'characters', 'all']) {
            totalCounts[field] = count[field]
        }
    }

    return totalCounts
}

Countable.live(editables, function (counter) {
    counts[this.id] = counter
})
```

Then you could just call the `sumCounts()` function whenever you want to know the total count, e.g. inside the `live` method.

Hope this works for your use case.

**Comment by RadLikeWhoa** [comment]
Assuming this issue is resolved or not relevant anymore, so I'm closing it. You can still reply if the issue remains.
