### ISSUE TITLE
Add support for just passing in a string?

### ISSUE THREAD

**Issue by grofit** [RadLikeWhoa/Countable#47]
Is it possible to just have a method like `once` which instead of taking the element instead just takes the html or word string and processes it?

**Comment by johndatserakis** [comment]
I do like the idea, but one thing you can do now to emulate that behavior is set your target div to `display: none` in the css. This way, the div doesn't show on the page and you can still do your thing.

**Comment by johndatserakis** [comment]
Definitely - I hear what you're saying. Would be nice to remove that dependency all together.

**Comment by RadLikeWhoa** [comment]
Now available in version [3.0.1](https://github.com/RadLikeWhoa/Countable/releases/tag/3.0.1). Thanks for the inputs.

**Comment by tageecc** [comment]
@RadLikeWhoa  thx for update, and can u publish the package on the npmjs，i can't find the version 3.0.1
