### ISSUE TITLE
Readme issue

### ISSUE THREAD

**Issue by hidekuro** [RadLikeWhoa/Countable#49]
the readme says `yarn add Countable` (package name starts with upper case). but this package name is wrong.

```
$ yarn add --dev Countable
yarn add v1.6.0
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/Countable: Not found".
```

use `countable` instead of `Countable` work fine.

**Comment by RadLikeWhoa** [comment]
Thanks for the heads-up, much appreciated.
