### ISSUE TITLE
Wrong counter on mobile

### ISSUE THREAD

**Issue by oclockvn** [RadLikeWhoa/Countable#51]
Hi @RadLikeWhoa 

Got this issue on mobile only (Android 7.0.0, Chrome 67)

I have a textarea with maxlength="3", it shows 3 characters but still count (see image below)

![image](https://user-images.githubusercontent.com/3783976/41087789-cd1c2544-6a67-11e8-9291-c6f924d76eaa.png)

Hope anyone fix it soon 😄

**Comment by RadLikeWhoa** [comment]
This seems to be an issue with Chrome on Android (https://caniuse.com/#feat=maxlength) and the way they handle the maxlength attribute. Text can be entered past the specified max length, but it is cut off once the area loses focus.

I don't think fixing this is in scope for Countable as it is such a specific issue for Chrome on Android and would essentially require overriding the input handling for textareas. Closing this for now.
